export const enum KeyCode {
  A = 'KeyA',
  B = 'KeyB',
  C = 'KeyC',
  D = 'KeyD',
  E = 'KeyE',
  F = 'KeyF',
  G = 'KeyG',
  H = 'KeyH',
  I = 'KeyI',
  J = 'KeyJ',
  K = 'KeyK',
  L = 'KeyL',
  M = 'KeyM',
  N = 'KeyN',
  O = 'KeyO',
  P = 'KeyP',
  Q = 'KeyQ',
  R = 'KeyR',
  S = 'KeyS',
  T = 'KeyT',
  U = 'KeyU',
  V = 'KeyV',
  W = 'KeyW',
  X = 'KeyX',
  Y = 'KeyY',
  Z = 'KeyZ',
  NUM0 = 'Digit0',
  NUM1 = 'Digit1',
  NUM2 = 'Digit2',
  NUM3 = 'Digit3',
  NUM4 = 'Digit4',
  NUM5 = 'Digit5',
  NUM6 = 'Digit6',
  NUM7 = 'Digit7',
  NUM8 = 'Digit8',
  NUM9 = 'Digit9',
  TAB = 'Tab',
  BACKSPACE = 'Backspace',
  CAPS_LOCK = 'CapsLock',
  L_ALT = 'AltLeft',
  L_SHIFT = 'ShiftLeft',
  ESC = 'Escape',
  SPACE = 'Space',
  PAGE_UP = 'PageUp',
  PAGE_DOWN = 'PageDown',
  BACKQUOTE = 'Backquote',
  MINUS = 'Minus',
  EQUAL = 'Equal',
  ENTER = 'Enter',
}

export const enum MouseButton {
  LEFT = 0,
  MIDDLE = 1,
  RIGHT = 2
}
